spring.application.name=microcrm

server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.directory=/proc/1/fd
server.tomcat.accesslog.prefix=1
server.tomcat.accesslog.suffix=
server.tomcat.accesslog.file-date-format=
server.tomcat.accesslog.buffered=false
server.tomcat.accesslog.pattern=%h %l %u %t "%r" %s %b %D