name: Trigger create infrastructure

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Terraform action"
        required: true
        default: "plan"
        type: choice
        options:
          - plan
          - apply
          - destroy
      environment:
        description: "Environment"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - prod

permissions:
  contents: read

jobs:
  call-Create-Infra:
    uses: Project6-Organisation/Project6-Integration/.github/workflows/_03_Create_Infra.yml@main
    with:
      action: ${{ github.event.inputs.action }}
      environment: ${{ github.event.inputs.environment }}
    secrets: inherit