name: Trigger application rollback

on:
  workflow_dispatch:
    inputs:      
      environment:
        description: "Environment"
        required: true
        default: "prod"
        type: choice
        options:
          - prod

permissions:
  contents: read
  packages: read

jobs:
  Trigger-Rollback:
    uses: Project6-Organisation/Project6-Integration/.github/workflows/_06_Rollback_Canary.yml@main
    with:
      environment: ${{ github.event.inputs.environment }}
    secrets: inherit