name: Deploy Infra with Terraform on EKS

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Terraform action"
        required: true
        default: "apply"
        type: choice
        options:
          - plan
          - apply
          - destroy

permissions:
  contents: read

jobs:
  call-Create-Infra:
    uses: Project6-Organisation/Project6-Integration/.github/workflows/_03_Create_Infra.yml@main
    with:
      action: ${{ github.event.inputs.action }}
    secrets: inherit