name: Continuous Deployment Workflow

on:
  workflow_dispatch:
    inputs:      
      environment:
        description: "Environment"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - prod

      image_tag:
        description: "Docker image tag to deploy"
        required: true
        default: "v1.6.0"

permissions:
  contents: read
  packages: read

jobs:
  Continuous-Deployment:
    uses: Project6-Organisation/Project6-Integration/.github/workflows/_04_Deployment.yml@main
    with:
      environment: ${{ github.event.inputs.environment }}
      image_tag: ${{ github.event.inputs.image_tag }}
    secrets: inherit