name: Promote Canary

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        options:
          - prod

permissions:
  contents: read

jobs:
  Trigger-Rollback:
    uses: Project6-Organisation/Project6-Integration/.github/workflows/_06_Promote_Canary.yml@main
    with:
      environment: ${{ github.event.inputs.environment }}
    secrets: inherit