name: Trigger application deployment

on:
  workflow_dispatch:
    inputs:      
      environment:
        description: "Environment"
        required: true
        default: "prod"
        type: choice
        options:          
          - prod

      image_tag:
        description: "Docker image tag to deploy"
        required: true
        default: "v1.6.0"

permissions:
  contents: read
  packages: read

jobs:
  Continuous-Deployment:
    uses: Project6-Organisation/Project6-Integration/.github/workflows/_03_Deployment_Appli.yml@main
    with:
      environment: ${{ github.event.inputs.environment }}
      image_tag: ${{ github.event.inputs.image_tag }}
    secrets: inherit