name: Create EKS Cluster

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  create-eks:
    runs-on: [self-hosted, project6]

    defaults:
      run:
        working-directory: integration/infra/eks

    steps:
      - name: Checkout integration repository
        uses: actions/checkout@v4
        with:
          repository: Project6-Organisation/Project6-Integration
          path: integration

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan

      - name: Terraform apply
        run: terraform apply -auto-approve