name: Trigger Integration Workflow
 
on:
  workflow_dispatch:
    inputs:
      info:
        description: "Use this to trigger the workflow manually"
        required: false
        default: "develop branch"

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: read
 
jobs: 

  call-generic-pipeline-develop:
    uses: Project6-Organisation/Project6-Integration/.github/workflows/01_Integration.yml@${{ github.ref_name }}
    with:
      origin: java
    secrets: inherit