name: Deploy EKS Infra

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Terraform action"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy

permissions:
  contents: read

jobs:
  eks-infra:
    runs-on: [self-hosted, project6]

    defaults:
      run:
        working-directory: integration/infra/eks

    steps:
      - name: Checkout integration repository
        uses: actions/checkout@v4
        with:
          repository: Project6-Organisation/Project6-Integration
          path: integration
      
      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        if: inputs.action == 'apply'
        run: terraform plan

      - name: Terraform apply
        if: inputs.action == 'apply'
        run: terraform apply -auto-approve

      - name: Terraform destroy
        if: inputs.action == 'destroy'
        run: terraform destroy -auto-approve