name: Trigger CD Workflow
 
on:
  workflow_dispatch:
    inputs:
        info:
          description: "Use this to trigger the workflow manually. You can select the branch to use, but the workflow will run on the develop branch"
          required: false
          default: "main branch"
    
permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: read
 
jobs: 

  Release-and-build-images:      
      uses: Project6-Organisation/Project6-Integration/.github/workflows/_02_Release_And_Docker.yml@main
      with:
        origin: manual-trigger
      secrets: inherit