name: Integration Workflow

on:
  push:
  pull_request: 

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: read

jobs:
  call-generic-pipeline-main:
    uses: Project6-Organisation/Project6-Integration/.github/workflows/01_Integration.yml@main
    secrets: inherit