name: Integration Workflow

on:
  push:
    branches:
      - "**"
  
  pull_request:
    branches:
      - "main"

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: read

jobs:
  call-generic-pipeline-main:
    uses: Project6-Organisation/Project6-Integration/.github/workflows/_01_Integration.yml@main
    secrets: inherit