name: Validate PR source for main

on:
  pull_request:
    branches:
      - main

jobs:
  validate-source-branch:
    # runs-on: [self-hosted, project6]
    runs-on: ubuntu-latest

    steps:
      - name: Ensure main PR comes from develop
        run: |
          echo "Base branch: ${{ github.base_ref }}"
          echo "Source branch: ${{ github.head_ref }}"

          if [ "${{ github.head_ref }}" != "develop" ]; then
            echo "PRs to main are only allowed from develop."
            exit 1
          fi